package conf

const (
	// DefaultDir ...
	DefaultDir = "."
	// DefaultFileExt ...
	DefaultFileExt = "*"
	// DefaultChunksSizeToScan ...
	DefaultChunksSizeToScan = 2048
	// DefaultSkipPaths ...
	DefaultSkipPaths = ".git,tmp"
)
